version: '3.9'

services:
  web:
    build: .
    container_name: ipm_challenge
    volumes:
      - .:/app
      - ./ipm-challenge/db.sqlite3:/app/ipm-challenge/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
